name: |-
  CD - Atmos stack deploy
  
  Deploy atmos stack
  
  ### Usage 
  
  ```yaml
    name: Feature Branch
    on:
      pull_request:
        branches: [ 'master' ]
        types: [opened, synchronize, reopened, closed, labeled, unlabeled]
  
    jobs:
      cd:
        uses: cloudposse/github-actions-workflows/.github/workflows/cd-atmos-stack-deploy.yaml@main
  ```
on:
  workflow_call:
    inputs:
      stack:
        description: The stack name.
        required: true
        type: string
      component:
        description: The component name.
        required: true
        type: string
      environment:
        description: Environment.
        required: true
        type: string
jobs:
  plan:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      # This is just to mock calling terraform plan. In reality, this would be a call to `atmos terraform plan`
      - run: echo "atmos terraform plan ${{inputs.component}} -s ${{inputs.stack}}"
