name: |-
  CI - Verify Docker image exists
  
  Verify Docker image exists on ECR

  ### Usage 

  ```yaml
    name: Release
    on:
      release:
        types: [published]

    jobs:
      ci:
        uses: cloudposse/github-actions-workflows/.github/workflows/ci-dockerized-app-verify.yml@main
        with:
          organization: $\{\{ github.event.repository.owner.login \}\}
          repository: $\{\{ github.event.repository.name \}\}
          version: $\{\{ github.event.release.tag_name \}\}
        secrets:
          ecr-region: $\{\{ secrets.ecr-region \}\}
          ecr-iam-role: $\{\{ secrets.ecr-iam-role \}\}
          registry: $\{\{ secrets.registry \}\}
          secret-outputs-passphrase: $\{\{ secrets.secret-outputs-passphrase \}\}

  ```

on:
  workflow_call:
    inputs:
      organization:
        description: "Repository owner organization (ex. acme for repo acme/example)"
        required: true
        type: string
      repository:
        description: "Repository name (ex. example for repo acme/example)"
        required: true
        type: string
      app:
        description: "Application name. Used with monorepo pattern when there are several applications in the repo"
        required: true
        type: string
      version:
        description: "Release version tag"
        required: true
        type: string
    secrets:
      ecr-region:
        description: "ECR AWS region"
        required: true
      ecr-iam-role:
        description: "IAM Role ARN provide ECR write/read access"
        required: true
      secret-outputs-passphrase:
        description: "Passphrase to encrypt/decrypt secret outputs with gpg. For more information [read](https://github.com/cloudposse/github-action-secret-outputs)"
        required: true
      registry:
        description: "ECR Docker registry"
        required: true
    outputs:
      image:
        description: "Docker Image"
        value: ${{ jobs.pull.outputs.image }}
      tag:
        description: "Docker image tag"
        value: ${{ jobs.pull.outputs.tag }}

permissions:
  id-token: write
  contents: read

jobs:
  pull:
    runs-on: ["self-hosted"]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          aws-region: ${{ secrets.ecr-region }}
          role-to-assume: ${{ secrets.ecr-iam-role }}

      - uses: cloudposse/github-action-docker-image-exists@0.1.0
        id: pull
        with:
          organization: ${{ inputs.organization }}
          repository: ${{ inputs.repository }}/${{ inputs.app }}
          registry: ${{ secrets.registry }}
          tag: ${{ inputs.version }}

      - uses: cloudposse/github-action-secret-outputs@0.1.1
        id: image
        with:
          secret: ${{ secrets.secret-outputs-passphrase }}
          op: encode
          in: ${{ steps.pull.outputs.image }}

    outputs:
      image: ${{ steps.image.outputs.out }}
      tag: ${{ steps.pull.outputs.tag }}
