name: |-
  Controller - Labels
  
  Label a pull request with one or more labels

  ### Usage 

  ```yaml
    name: Label pull request
    on:
      workflow_call:

    jobs:
      label:
        uses:  cloudposse/github-actions-workflows/.github/workflows/controller-labels.yml@main
        with:
          labels: ['ready-for-review']
  ```

on:
  workflow_call:
    inputs:
      labels:
        description: The labels' name to be added. Must be separated with line breaks if there are multiple labels.
        type: string
        required: true
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'

jobs:
  add-labels:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ${{ inputs.labels }}