name: |-
  Controller - Create Release branch
  
  Create `release/{version}` branch for the release 

  ### Usage 

  ```yaml
    name: Main branch
    on:
      release:
        types: [published]

    jobs:
      do:
        uses: cloudposse/github-action-workflows/.github/workflows/controller-hotfix-release-branch.yml@main
        with:
          version: $\{\{ github.event.release.tag_name \}\}
  ```  

on:
  workflow_call:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

jobs:
  release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create branch for specific version
        uses: satya-500/create-branch-from-tag@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          branch: release/${{ inputs.version }}
          from: tags/${{ inputs.version }}

